name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test & Lint
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: mvz_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:test@localhost:5432/mvz_test
        run: |
          npx prisma generate
          npx prisma db push

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:test@localhost:5432/mvz_test
        run: yarn test

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build project
        run: yarn build

      - name: Create deployment archive
        run: |
          tar -czf deployment.tar.gz \
            dist/ \
            node_modules/ \
            package.json \
            prisma/ \
            .env.example \
            ecosystem.config.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment
          path: deployment.tar.gz
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Server
    needs: [test, build]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script_stop: true
          script: |
            # Set variables
            APP_DIR="/opt/mvz-bot"
            BACKUP_DIR="/opt/mvz-bot-backups"
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            
            # Create backup directory
            mkdir -p $BACKUP_DIR
            
            # Backup current installation if exists
            if [ -d "$APP_DIR" ]; then
              echo "Creating backup..."
              cp -r $APP_DIR $BACKUP_DIR/mvz-bot-$TIMESTAMP
              
              # Stop the application
              pm2 stop mvz-bot || true
              
              # Keep only last 5 backups
              cd $BACKUP_DIR
              ls -t | tail -n +6 | xargs -r rm -rf
            fi
            
            # Create app directory
            mkdir -p $APP_DIR
            cd $APP_DIR
            
            # Download deployment archive
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -L "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/deployment" \
                 -o deployment.zip
            
            # Extract deployment
            unzip -q deployment.zip
            tar -xzf deployment.tar.gz
            rm deployment.zip deployment.tar.gz
            
            # Setup environment if not exists
            if [ ! -f .env ]; then
              cp .env.example .env
              echo "⚠️  Please configure .env file with production values"
            fi
            
            # Run database migrations
            npx prisma generate
            npx prisma migrate deploy
            
            # Start application
            pm2 start ecosystem.config.js --env production
            pm2 save
            
            echo "✅ Deployment completed successfully!"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🎉 Deployment successful!"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi